[package]
name = "bip39"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.2"
openssl = "0.10.66"
argon2 = "0.5.3"
sha2 = "0.10.8"
rpassword = "7.3.1"
hex = "0.4.3"
structopt = "0.3.26"
